apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "state-service"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
  annotations:
    texas.nais.io/enabled: "true"
spec:
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        databases:
          - name: emottak-statedb
            envVarPrefix: POSTGRES
  webproxy: true
  image: {{image}}
  liveness:
    path: "/internal/health/liveness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
    logging:
      destinations:
        - id: elastic
        - id: loki
  prometheus:
    enabled: true
    path: /prometheus
  readiness:
    path: "/internal/health/readiness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "1000m"
      memory: "1024Mi"
    requests:
      cpu: "200m"
      memory: "512Mi"
  ingresses:
    - "https://state-service.intern.dev.nav.no"
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvtokt
        mountPath: /secret/serviceuser
  accessPolicy:
    outbound:
    inbound:
      rules:
        - application: azure-token-generator
          namespace: aura
          cluster: dev-gcp
  env: